# Generated by Django 5.1.6 on 2025-03-31 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'db_table': 'otps',
                'indexes': [models.Index(fields=['key'], name='otps_key_496193_idx'), models.Index(fields=['created_at'], name='otps_created_b35e98_idx')],
            },
        ),
    ]
