__name__ = "df-wallet-user-service"
__display_name__ = "DF Wallet User Service API"
__description__ = "Developers Foundry Wallet System User Service RESTful API"
__version__ = "1.2.0"
__author__ = "Ogidi Ifechukwu (ogidiifechukwu6@gmail.com)"
