__name__ = "df-wallet"
__display_name__ = "DF Wallet API"
__description__ = "Developers Foundry Wallet System RESTful API"
__version__ = "1.0.2"
__author__ = "Ogidi Ifechukwu (ogidiifechukwu6@gmail.com)"
